jobs:
# jobs for the dv pipeline from CI thru TEST environment
# manifest gen for VISUALIZER
  - name: pipelines-demo-manifest
    type: manifest
    steps:
      - IN: samplepipelinesdemo
      - TASK: managed

#/ manifest gen for VISUALIZER

# TEST deployment for VISUALIZER to Amazon ECS
  - name: pipelines-demo-deploy
    type: deploy
    steps:
      - IN: pipelines-demo-manifest
      - IN: docker-options
      - IN: ecs-cluster
      - TASK: managed
        deploymethod: upgrade
# / TEST deployment for VISUALIZER to Amazon ECS

# Connect CI with dv-img resource
  - name: samplePipelinesDemo_runCI
    type: runCI
    steps:
      - OUT: samplepipelinesdemo
# / Connect CI with dv-img resource
